services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root" # токен для dev режима
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - local

  crypto-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-crypto-service.rule=Host(`api.kontora-dev.ru`) && PathPrefix(`/auth-crypto-service/api/v1`)"
      - "traefik.http.routers.auth-crypto-service.entrypoints=websecure"
      - "traefik.http.routers.auth-crypto-service.tls.certresolver=myresolver"
      - "traefik.http.services.auth-crypto-service.loadbalancer.server.port=8000"
      - "traefik.http.routers.auth-crypto-service.service=auth-crypto-service"
      - "traefik.docker.network=global"
    networks:
      - local
      - global

networks:
  local:
  global:
    external: true
