serivces:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_CLUSTER_ADDR: "https://vault:8201"
    volumes:
      - vault_data:/vault/file
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/vault-config.hcl
    networks:
      - auth-crypto-network

networks:
  auth-crypto-network:
    external: true
